//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAOV.CommandTools.AzTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AzCommands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AzCommands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAOV.CommandTools.AzTools.AzCommands", typeof(AzCommands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az account show --query &quot;{id:id, name:name, state:state, tenantDisplayName:tenantDisplayName, tenantId:tenantId, userName:user.name, userType:user.type}&quot;.
        /// </summary>
        internal static string AccountShow {
            get {
                return ResourceManager.GetString("AccountShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az account set --subscription @@@.
        /// </summary>
        internal static string AzAccountSetSubscription {
            get {
                return ResourceManager.GetString("AzAccountSetSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az account subscription list --query &quot;[].{displayName:displayName, state:state, subscriptionId:subscriptionId}&quot;.
        /// </summary>
        internal static string AzAccountSubscriptionList {
            get {
                return ResourceManager.GetString("AzAccountSubscriptionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az keyvault secret show --vault-name @@@KeyVault --name @@@SecretName --query &quot;value&quot;.
        /// </summary>
        internal static string AzGetKeyVaultSecretValue {
            get {
                return ResourceManager.GetString("AzGetKeyVaultSecretValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az keyvault list --query &quot;[].{name:name, resourceGroup:resourceGroup, location:location}&quot;.
        /// </summary>
        internal static string AzKeyVaultList {
            get {
                return ResourceManager.GetString("AzKeyVaultList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az keyvault secret list --vault-name @@@ --query &quot;[].{name:name, enabled:attributes.enabled}&quot;.
        /// </summary>
        internal static string AzKeyVaultSecretsList {
            get {
                return ResourceManager.GetString("AzKeyVaultSecretsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az login --service-principal -u @@@User -p @@@Secret --tenant @@@Tenant  --query &quot;[].{id:id, isDefault:isDefault, name:name, state:state}&quot;.
        /// </summary>
        internal static string AzLogin {
            get {
                return ResourceManager.GetString("AzLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az logout.
        /// </summary>
        internal static string AzLogout {
            get {
                return ResourceManager.GetString("AzLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az group list --query &quot;[].{name:name, location:location, provisioningState:properties.provisioningState}&quot;.
        /// </summary>
        internal static string AzResourceGroupList {
            get {
                return ResourceManager.GetString("AzResourceGroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az resource list --resource-group @@@ --query &quot;[].{name:name, location:location, provisioningState:provisioningState, type:type}&quot;.
        /// </summary>
        internal static string AzResourceGroupResources {
            get {
                return ResourceManager.GetString("AzResourceGroupResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az version.
        /// </summary>
        internal static string AzVersion {
            get {
                return ResourceManager.GetString("AzVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        internal static string ClearScreenLinux {
            get {
                return ResourceManager.GetString("ClearScreenLinux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cls.
        /// </summary>
        internal static string ClearScreenWindows {
            get {
                return ResourceManager.GetString("ClearScreenWindows", resourceCulture);
            }
        }
    }
}
