//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAOV.CLI.AzTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AzCommands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AzCommands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAOV.CLI.AzTools.AzCommands", typeof(AzCommands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az login --service-principal -u @@@User -p @@@Secret --tenant @@@Tenant  --query &quot;[].{id:id, isDefault:isDefault, name:name, state:state}&quot;.
        /// </summary>
        internal static string Account_Login {
            get {
                return ResourceManager.GetString("Account-Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az logout.
        /// </summary>
        internal static string Account_Logout {
            get {
                return ResourceManager.GetString("Account-Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az account set --subscription @@@SubscriptionId.
        /// </summary>
        internal static string Account_SetSubscription {
            get {
                return ResourceManager.GetString("Account-SetSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az account show --query &quot;{id:id, name:name, state:state, tenantDisplayName:tenantDisplayName, tenantId:tenantId, userName:user.name, userType:user.type}&quot;.
        /// </summary>
        internal static string Account_Show {
            get {
                return ResourceManager.GetString("Account-Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az account subscription list --query &quot;[].{displayName:displayName, state:state, subscriptionId:subscriptionId}&quot;.
        /// </summary>
        internal static string Account_SubscriptionList {
            get {
                return ResourceManager.GetString("Account-SubscriptionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az acr repository list --name &quot;@@@ACRName&quot;.
        /// </summary>
        internal static string ACR_Repositories {
            get {
                return ResourceManager.GetString("ACR-Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az acr repository show-tags --name &quot;@@@ACRName&quot; --repository &quot;@@@ACRRepositoryName&quot;.
        /// </summary>
        internal static string ACR_RepositoryTags {
            get {
                return ResourceManager.GetString("ACR-RepositoryTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az acr show --name &quot;@@@ACRName&quot; --query &quot;{anonymousPullEnabled:anonymousPullEnabled, dataEndpointHostNames:dataEndpointHostNames[0], id:id, location:location, loginServer:loginServer, name:name, networkRuleBypassOptions:networkRuleBypassOptions, networkRuleSetDefaultAction:networkRuleSet.defaultAction, provisioningState:provisioningState, publicNetworkAccess:publicNetworkAccess, resourceGroup:resourceGroup, skuName:sku.name, skuTier:sku.tier, type:type, zoneRedundancy:zoneRedundancy}&quot;.
        /// </summary>
        internal static string ACR_Show {
            get {
                return ResourceManager.GetString("ACR-Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az apim api list --resource-group @@@ResourceGroup --service-name @@@APIM --query &quot;[].{id:id, displayName:displayName, name:name, path:path, resourceGroup:resourceGroup, serviceUrl:serviceUrl, subscriptionRequired:subscriptionRequired}&quot;.
        /// </summary>
        internal static string APIManagement_List {
            get {
                return ResourceManager.GetString("APIManagement-List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az apim api operation list --resource-group @@@ResourceGroup --service-name @@@APIM --api-id @@@APIs --query &quot;[].{id:id, displayName:displayName, method:method, name:name, resourceGroup:resourceGroup, statusCode:statusCode}&quot;.
        /// </summary>
        internal static string APIManagement_OperationList {
            get {
                return ResourceManager.GetString("APIManagement-OperationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az extension add --name @@@ExtensionName.
        /// </summary>
        internal static string AzureCli_ExtensionAdd {
            get {
                return ResourceManager.GetString("AzureCli-ExtensionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az extension remove --name @@@ExtensionName.
        /// </summary>
        internal static string AzureCli_ExtensionRemove {
            get {
                return ResourceManager.GetString("AzureCli-ExtensionRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az extension list-available --query &quot;[].{name:name, summary:summary, version:version}&quot;.
        /// </summary>
        internal static string AzureCli_ExtensionsAvailableList {
            get {
                return ResourceManager.GetString("AzureCli-ExtensionsAvailableList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az extension list --query &quot;[].{name:name, summary:summary, version:version}&quot;.
        /// </summary>
        internal static string AzureCli_ExtensionsInstalledList {
            get {
                return ResourceManager.GetString("AzureCli-ExtensionsInstalledList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az extension update --name @@@ExtensionName.
        /// </summary>
        internal static string AzureCli_ExtensionUpdate {
            get {
                return ResourceManager.GetString("AzureCli-ExtensionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az upgrade --yes.
        /// </summary>
        internal static string AzureCli_Upgrade {
            get {
                return ResourceManager.GetString("AzureCli-Upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az version.
        /// </summary>
        internal static string AzureCli_Version {
            get {
                return ResourceManager.GetString("AzureCli-Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az keyvault list --query &quot;[@@@AzureQueryFilter].{id:id, name:name, resourceGroup:resourceGroup, location:location}&quot;.
        /// </summary>
        internal static string KeyVault_List {
            get {
                return ResourceManager.GetString("KeyVault-List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az keyvault network-rule list --resource-group @@@ResourceGroup --name @@@KeyVault.
        /// </summary>
        internal static string KeyVault_NetworkRule {
            get {
                return ResourceManager.GetString("KeyVault-NetworkRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az keyvault secret list --vault-name @@@KeyVault.
        /// </summary>
        internal static string KeyVault_SecretList {
            get {
                return ResourceManager.GetString("KeyVault-SecretList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az keyvault secret show --vault-name @@@KeyVault --name @@@SecretName --query &quot;{id:id, name:name, value:value}&quot;.
        /// </summary>
        internal static string KeyVault_SecretShow {
            get {
                return ResourceManager.GetString("KeyVault-SecretShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az group list --query &quot;[@@@AzureQueryFilter].{id:id, name:name, location:location, provisioningState:properties.provisioningState}&quot;.
        /// </summary>
        internal static string ResourceGroup_List {
            get {
                return ResourceManager.GetString("ResourceGroup-List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az resource list --resource-group @@@ResourceGroup --query &quot;[].{id:id, name:name, location:location, provisioningState:provisioningState, type:type}&quot;.
        /// </summary>
        internal static string ResourceGroup_ResourcesList {
            get {
                return ResourceManager.GetString("ResourceGroup-ResourcesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az resource list --query &quot;[@@@AzureQueryFilter].{id:id, name:name, location:location, provisioningState:provisioningState, resourceGroup:resourceGroup, type:type}&quot;.
        /// </summary>
        internal static string ResourceGroup_ResourcesListInSubscription {
            get {
                return ResourceManager.GetString("ResourceGroup-ResourcesListInSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az resource list --query &quot;[@@@AzureQueryFilter &amp;&amp; type==&apos;@@@ResourceType&apos;].{id:id, name:name, location:location, provisioningState:provisioningState, resourceGroup:resourceGroup, type:type}&quot;.
        /// </summary>
        internal static string ResourceGroup_ResourcesListInSubscriptionFilterType {
            get {
                return ResourceManager.GetString("ResourceGroup-ResourcesListInSubscriptionFilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az network vnet subnet show --ids @@@Ids --query &quot;{id:id, addressPrefix:addressPrefix,addressPrefixes:addressPrefixes,name:name,provisioningState:provisioningState,networkSecurityGroup:networkSecurityGroup.id,routeTable:routeTable.id}&quot;.
        /// </summary>
        internal static string Subnet_Show {
            get {
                return ResourceManager.GetString("Subnet-Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az network vnet list --query &quot;[@@@AzureQueryFilter].{id:id, addressSpace:addressSpace.addressPrefixes,name:name,provisioningState:provisioningState,resourceGroup:resourceGroup,subnets:subnets[*].id}&quot;.
        /// </summary>
        internal static string Vnet_List {
            get {
                return ResourceManager.GetString("Vnet-List", resourceCulture);
            }
        }
    }
}
